### ISSUE TITLE
Intro/Read in raw data

### ISSUE THREAD

**Issue by ebeecher** [ebeecher/sexharassment#2]
Hi @AaronGullickson ,

Here to let you know that I'm (finally) up to date on the assignments for our own projects. I wrote an intro, edited the readme for the data and wrote a data and methods section, and read in my raw data. I have to edit both the intro and data and methods section, so I didn't yet knit it into a PDF, but wanted you to know that it is basically all there.

**Comment by ebeecher** [comment]
@AaronGullickson I'm also probably going to have to come into your office hours this week again because I'm having immense difficulty keeping my files organized. Something is happening that causes a million folders to be made and my rpoj file keeps disappearing. When I create a new rproj file, another million folders are created. It is creating quite the organizational headache.

**Comment by AaronGullickson** [comment]
@ebeecher Everything looks good, except that the raw data is not actually up on the GitHub site. If you can push that up, it would be great.

The folder issue sounds very frustrating and strange. Once you get the raw data up to GitHub, I would recommend just making a fresh clone of the project from GitHub. Once you are sure that one is working correctly, get rid of the problem one. Happy to look it over in OH or after class as well.
