### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by ebeecher** [ebeecher/sexharassment#3]
Hi @AaronGullickson 
I don't really know how to explain to you what's happening or why I'm confused, but I was trying to recode question 28 and I can't figure out how the answers were coded at all. If you could take a look at that and the work I've already done, that would be fantastic.

Thank you!

**Comment by AaronGullickson** [comment]
@ebeecher Ok, there are two issues here. 

## Trimming whitespace

Before, we can talk about the central coding issue, I am realizing there is a problem in the way read_fwf reads in by default. By default, it chops extra white space at the beginning and end of fields. This means that

"1 11 1 "
and 
"1 11 1"

will be interpreted the same even though everything will be offset in the wrong place in the first one. You can fix this in your `read_fwf` command by adding the argument `trims_ws=FALSE`. You will need to check your existing code as this might possible affect it. 

## Binary coding

Once that is corrected, then it looks like questions that were checked as "mark all that apply" were recorded using a binary logic. Q28 has 10 characters. A 1 in a given index means the box was checked and a space means it wasn't. The only uncertainty here is the ordering but I think its reasonable to assume it goes from the top category to the bottom. 

In that case, you can use the `substr` command to extract TRUE/FALSE variables for each of the possible categories that individuals could have marked in response. Here is an example with the first category of work assignments/conditions got worse:

```r
sexharass$work_worse <- substr(sexharass$Q28, 1, 1)=="1"
```

The `1,1` part of `substr` identifies the starting and ending character index for pulling the substring. So just replace that with `2,2` to get the next one and so on.

**Comment by ebeecher** [comment]
Hi @AaronGullickson 
I added the trim whitespace command and received an error message, saying that it is an "unused argument."

**Comment by AaronGullickson** [comment]
I think you need to update the `readr library. I had this problem as well. First to check, run these commands:

```r
library(readr)
sessionInfo()
```

That will tell you what version of `readr` is installed, among other things. You want 1.3 at least - I am guessing yours is 1.1. To upgrade, just re-install:

```r
install.packages("readr")
```

It will probably give you a message about restarting R, which is fine. After that is done, run the first command and you should be updated to 1.3.

**Comment by AaronGullickson** [comment]
@ebeecher forgot to tag you for the comment above.

**Comment by ebeecher** [comment]
@AaronGullickson Hi, I think I completed my analytical dataset?? If you have a moment, let me know what you think, otherwise I'll be in your office at 11am tomorrow.

**Comment by ebeecher** [comment]
@AaronGullickson actually there are still problems with it, so I'll just talk it through with you tomorrow

**Comment by ebeecher** [comment]
hi @AaronGullickson 
I wanted to create a factor out of my outcome variables, like you would with the highest degree achieved, with the variables bad_outcome, neutral_outcome, and good_outcome, but I can't figure it out using the slides from last term even though there is a section about it there. I think in the example you used, you weren't using an established dataset and I'm confused about where to begin. Could you point me in the right direction? (only if you get this in time, otherwise I'll turn something in without it) Thanks!

**Comment by ebeecher** [comment]
Hi @AaronGullickson 
Also, everything seemed to be working fine with you yesterday, but now R is saying that it can't find my object "incident" every time I source all of organize data at once or when I try to create any kind of figure in the lab notebook page. I don't know how to fix it because it works sometimes, but not other times.

**Comment by AaronGullickson** [comment]
@ebeecher You could use an ordered/cumulative logit model. If you want to do that assuming parallel effects you can use the `polr` function in the library `MASS`. For full non-parallel effects you need the `vglm` command in the `VGAM` library. However, I don't think the payoff will be that great. I think the most important cutpoint here is bad outcome vs. everything else, so I would stick to that for this project. 

On the incident object not being found, from what I can see on GH, you are not saving the incident variable at the bottom of your organize_data script when you call the subset command. Just add it to the chain of variables there, re-source, and you should be good.
